// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzuxilmdiddxowmqobuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dXhpbG1kaWRkeG93bXFvYnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MTI3NDYsImV4cCI6MjA4OTE4ODc0Nn0.4q0sA2EcMZ3dsVqls6ZpmWDZbXUyF1O9zi_Cg9a4oFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});